#+AUTHOR: SnootierMoon
#+OPTIONS: author:nil date:nil num:nil toc:nil
#+TITLE: SnootPlugin

This is my first (and probably last) project with Bukkit/Spigot. This is also my first project with Java.

This plugin was designed for servers with survival worlds (such as the overworld, nether and end) and creative worlds. However, it can be used for any survival server by denying the permissions for the creative world commands.

** Installation

*** For survival (SMPs):

 - Slap the jar into your =/plugins/= and you're set.
 - Deny permissions to players for:
   - =snoot.survival= (allows them to join/leave survival worlds)

*** For survival/creative: 

 - Slap the jar into your =/plugins/=.
 - Register the creative worlds using =/config world-type [world] creative= on each creative world.
 - Register the survival worlds using =/config world-type [world] survival= on each survival world.

** Command Usage

You can get a list of commands by doing =/help SnootPlugin=.

To get information on a command, type the command with a question mark as the only argument: =/command ?= or =/command subcommand ?=

** Features

*** Current  

 - chairs: =/chairs=
 - chatcolor: =/chatcolor=
 - nicknames =/nick=
 - tags =/tags=
 - utility:
   - commands for managing survival/creative worlds: =/survival leave=, =/survival join=, =/survival list=
   - nearby players command: =/near=
   - list and test color codes: =/colors=
   - =./= to =/=

*** Todo (in order)

 - inventory GUI =/menu=
 - bannermaker =/bannermaker=
 - trails =/trails=
 - colored signs
 - default command overrides: =/time=, =/teleport=
 - disguises
 - pets
