name: SnootPlugin
main: snoot.Main
version: 6.9.420
author: SnootierMoon
description: Snoot's epic plugin

commands:
  chairs:
    description: Sit on chairs
  chatcolor:
    description: Change the color of your chat messages
    aliases: chatcolour
  colors:
    description: List all chat colors
    aliases: colours
  nick:
    description: Change your nickname
  survival:
    description: Join and leave the survival world
  tags:
    description: Create and equip tags

permissions:
  snoot.*:
    default: true
    children:
      snoot.chairs: true
      snoot.chat.*: true

  snoot.chairs:
    default: true
    description: allows you to sit on chairs

  snoot.chat.*:
    default: true
    children:
      snoot.chat.color: true
      snoot.chat.nick: true
      snoot.chat.tags.*: true
  snoot.chat.color:
    default: true
    description: allows you to modify your chat color
  snoot.chat.nick:
    default: true
    description: allows you to modify your nickname
  snoot.chat.tags.*:
    default: true
    children:
      snoot.chat.tags.modify: true
      snoot.chat.tags.use: true
  snoot.chat.tags.modify:
    default: true
    description: allows you to create and use tags
  snoot.chat.tags.use:
    default: true
    description: allows you to create and use tags
