name: SnootPlugin
main: snoot.Main
version: 6.9.420
author: SnootierMoon
description: Snoot's epic plugin

commands:
  chairs:
    description: /chairs ? for more info
    permission: snoot.chairs
  chatcolor:
    aliases: chatcolour
    description: /chatcolor ? for more info
    permission: snoot.chat.color
  colors:
    aliases: colours
    description: /colors ? for more info
    permission: snoot.colors
  near:
    description: /near ? for more info
    permission: snoot.near
  nick:
    description: /nick ? for more info
    permission: snoot.chat.nick
  tags:
    description: /tags ? for more info
    permission: snoot.chat.tags

permissions:
  snoot:
    default: true
    children:
      snoot.chairs: true
      snoot.colors: true
      snoot.chat: true
      snoot.near: true
      snoot.survival: true

  snoot.chairs:
    default: true
    description: allows you to use /chairs

  snoot.colors:
    default: true
    description: allows you to use /colors

  snoot.chat:
    default: true
    children:
      snoot.chat.color: true
      snoot.chat.nick: true
      snoot.chat.tags: true
  snoot.chat.color:
    default: true
    description: allows you to use /chatcolor
  snoot.chat.nick:
    default: true
    description: allows you to use /nick
  snoot.chat.tags:
    default: true
    children:
      snoot.chat.tags.modify: true
      snoot.chat.tags.use: true
  snoot.chat.tags.modify:
    default: true
    description: allows you to change tags with /tags
  snoot.chat.tags.use:
    default: true
    description: allows you to equip tags with /tags

  snoot.near:
    default: true
    description: allows you to use /near
